[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[[services]]
name = "code-error-microservice"
protocol = "tcp"

[[services.ports]]
port = "3030"
internal_port = "3030"
